spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  rabbitmq:
    host: 192.168.203.203
    port: 5672
    username: admin
    password: admin
    virtualHost: /
    publisher-returns: true
    #发送端确认；
    publisher-confirm-type: correlated
    #手动ack机制
    listener:
      type: simple
      simple:
        acknowledge-mode: manual  #手动确认模式。


server:
  port: 15000


app:
  pay:
    alipay:
      app_id: 2021000120619003
      merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCkBbLz6vMjJUjibeAmbqj7lpkqs/BR9B2D6XOOtIRIsmtES5+0JmDX3M8yr/u4451LuZJ3zpQG0P+zh3MJiuZhe97YlzSNt8mnpYmsOc4Uhhi1md0A96NZBnh+YGuIk4vbXPh9DcO03Y2BAcq2mMafvQuVatr88z96GsQyb6Pec8BHQ50AnwAuE3QL/ph2KIFjTfhUIIWxBd0GV+kQt0Yq9G+ydNDM0ftZJt3WWK5x1BgBpK8u7G9qz4+1uPyfXiRW2aUF0BMqQPnGX9akrYJ2gbChjqU3Ab0gXJrKy8Z9b9H7R+Z5OxLLCK5n5zSscpNMnbHN/83uJDQ+6DnpVskTAgMBAAECggEBAJlJFi+sMCN1UcMCikuAeX3+BRCKbxo3+Glx/+OqwkGqNGL0BcF3aGPz4NNu8eGdHkBJoh9DOMWSBpWCDTkqzRjniaCC1sNmshdxtdL1hqlZlLgKniasR8UILg11EKnnsfmEzlkYRwC9WOPqh8bTyjQ4mR2/af6hWX5Ei3zTJqLZrPxtuY6i2eNUxSFQR1b50DnEgbKqGCFpOj6u8KPPl+iV5QIMDHx2GLMhWqOuyFVWmsv3YjDCGOPRgQqc8lCSO5BlJh8e4DGdClHn6llDV/x0W3+9YrMCbFWEOql6JBfE0Lh7l5mifwlF9TJnfVVmT7Ok53e7+phMgiFaonay8wkCgYEA0seYOJtDtZUqIFDBXc9usi9V//4dCLf8yWLPVUQa+gFLUhwOcJN9VZjiBHRpolRQ3m97I0whCroqK+mQTYdbFJ87qFX+5wPmJtHg/mpcYeappWVqTDkGisuyBS3mlbMnZyBh7Fad0Mx0YXGIa/koE35QBCJjDullHZG2v9sfj1UCgYEAxzYaI97zCWZrwXWFy8bklJVGgamZDxJALAuFmqnc5+Jt6ROznLME0R2Q4oHD7bCmaf3TIfX+yzMrzNXVz7o8ZjcsVhMlUZ2PxRHrlt8rW4XfqOAkFi47d8hQlZSmPH1jNkfEqNqbyKBs260EISUzR7E56nVqSUoK+JL/3QTo5scCgYBu9+PdEWkRRSm7f6h9wgJuTtuA/YC9oVe1ko7DPirRqjLEVL8JZ6zZjraXT855RtiYcqqqh57xrdcb7UgqePNrpPVch4G+j9/wWhiQ+OAQLsbrq7vNy0v1cI4ViffWok5BTdwf9+34ClvPHV2MMs11jc+EjbIHHLs+WQOUeEFiTQKBgA0LEs0UdO9BoH6LNlZwUFkWKQamVxowhLkdjALjak5Yef/PxWvWINOcTvc1reFrNoosD13i4Grnj8+alKREOl4q8KE2IbRlT5uEn9tCA3G7ozhIbLRzFHu0Rup0UCoXv543Nr4jih2pu1bqziFpcSEZjoQ2ad4glfVOkqgjASjTAoGAPHPNn/3IzS4YcruzGruWxCixXFCkMbV9l+q3A2KrpeIlX+odYorHPPG5FNHEN4T8gIuO+JoDL83o41pyVo3+ntxZgNEqncUWeRNdwbXhUqzMPloQNtPaXwZtbwjfhIuYL2qOjCZ49mpl3znTv4dRWS3bhzQVUPizuswN2ae77yg=
      alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmYUYwy6h8XlIb5ycsR1QOOyZVZaLFp4LVf1wsxe6nofUBz3p+LlMvtMoTCGOLcbaviw3JFngbsxcW9Zt+PSIKYG8vIq7Dv081R/uU4LxU4450iKh05IxH2bQa3TBNDZ9Oqojbd1unYi5tslfxRYlBzKiV11puVz2rUlPwrObtN9UWIUkS+YqcfmUSLOhDl4u0T9Ab03uN4jTTJtGqLQN7MxlygzEL35B2bcW3o6u7rCa76Q7q/9NAACDPohytsDM89Ho3AIy8Nx3P/IHIo9VM29FRJONJ9/a3Z9/OeSG0AbjSTSwJehw+zMCWLZ928veby8sIj0P+nAasbpdWgjcFwIDAQAB
      notify_url: http://59e8av.natappfree.cc/api/payment/notify/success
      return_url: http://payment.gmall.com/pay/success.html
      sign_type: RSA2
      charset: utf-8
      gatewayUrl: https://openapi.alipaydev.com/gateway.do



#      app_id: 2021000120617043
#      merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCEQ/ShrkE4/3QDzUwJ/1d+TVdb5DqjX+de5yQL83UMZTQtHBNOGt4zF0UVMl2uYiXS9QJEDrUtV9z9V7ke3aT5L4fe60MA7mmRuGps7nIe/jfc/vu0q648uut4PPLAYjD13WC1s7zec7N5r7roUI3bxVZqHL2mZahlags1EnKQ2H2zyFZmY2ndRNjnF5umNZFyNVXP4vkQjoZYZWVM0TKodYQOPPfxJhbNgskwtPhCmBKnK20+h4/hFy4GY9O7xVVDfisIoqxG8TIn4OTgLXJNVQhbzZxEdzgcAQlH4sunXucATHDlbjzsYKKvKazO6vx159+dHID4PMBYZ4MGe6LhAgMBAAECggEAQBI3N/cUq0q75XeWxSUHOiy3C9GUQj4b85IemRd3dOi1jMCT7XsAdlloYqtCTE5JKlb7oQJK68srRyIuj/AokXlf5TGsBJB5XVirXVdouvDFGO3/+nZL8ilOFbHYmi82rnNt/Lcz38LGh0UEUrNq9LI0eTSw/iEyoOXsxenIy7cQ+bkCrcQW2fNvPYVqaFvZNw2PISm6B2768++53LqpfbU8teySUenrH2dApTfkNBD8kZsVtfvlZ3+iCesOgVmxrgAPb6Y7g07ES/x9jnQymuFZs7k7gJEKKomVR9BtBvLQIoH7WelwaFjJO4SSk1snqTszWrBtXHcemjfLO7N7kQKBgQDFp3GiH3oUrf5QnCMGKkFXf4Z6kjHu5A6i+0aJhTeh/xJH2JMU71Ch/+jAc48UEC1ol28+sjEdw5frp63zHq7GmW4a0iHQ2UoWMScfqeyxMCzTKAt+84S/sZZ3lbG5FllExWcPkKx9MoM7DN8OaV4/OcFqUh1mvtKf0QhlOnETtQKBgQCrTyWiDgHl5X94EaIJLTvLrUvXEPJrStn5KSb45vzicwg1SiSt++vRFxd7R9s715vz8eLHzJ31xuqRPsLXKu2Nh5/iisnTImpqosBexTu8/BBTi6VI5wRuNdvXlugEJT4/p/k1yaSD5xvpDgRJMhS7+VGmpu7gtNWh6sUvCpol/QKBgQDFOEPhYgkdc1OsOW+VKjqSxRN5YEDkvriAFbwXYk7VnL8v40E3hWdujfw/c88TVOUKVPhSldj+evku0dx3F2mLjvLXXk8Rpo8PP7JrHNGpJ4nClFWMMg6Ge/vIjRyNs2gVf+dLF6+VKP7awAgdyDObYNTGcvMVX1io0RnQcBT+dQKBgBAKrFJ9j03w7LvYotzLIJNVGgn8q0bCzqCXau/Z6YpnDTi4RbEJKy78Q5Wmx+/Vo+P3Ha5qCcyvIN4TC3nMqkwbjCxRpM6hpWdw8CSvwYVT8U9xfzvRbkfHwVtx5S4mMqsRVrPjuwUjCikLx/j2uJxVn4DElw/xvyOXcXmTO5YdAoGAeLqaTL14VjArmDGnBGN40mJaPIytBqTL02kNo6iEhimGO+0JenWbMU9TOcJndb5OMybU9TgAuD+RQEoQxeDTACe0K+2wGkd7MHjp1+t5CRa29fkFHscXAzyimQJcEpECV1ZOqZphMrgsTroLoChWi1dObKfSpmxCnlT+PdCAlS4=
#      alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAllLsKGFsM7gAJ4uiYV9r70IMb82J5He+6ZBqpPmYSPNMM8X5EWm/F6k1bEQTtWKa+BGmMYnh+B6zyxnTqj5SfufieKQpzQR4HeWEacFF3Deard5R+TAgEoVqkldLDb/FvlYbI/9UljkhwmBh4jmztli80eYj5epWe4rPr/6F3/I6omumeND08b/4vDV2tUyEfScS888X1dvWekHfl6YSxTB6vmJjDDvAwrV67h8qAtKq9YMYvw4cj7KgE2tJ3dmLUjOdbCn7i7gxUoAgyVQ3Kx3m+Ip6ft6xerkFSWoR/p+SH9f2Du/7TAyoYve1xcVfMhh+fnj5MzEudN2ISM2LpQIDAQAB
#      sign_type: RSA2
#      charset: utf-8
#      gatewayUrl: https://openapi.alipaydev.com/gateway.do