server:
  port: 13000

spring:
  profiles:
    include: sharding
  redis:
    host: 192.168.203.203
    password: Hj123!@!
    lettuce:
      pool:
        max-active: 16
        min-idle: 0
  rabbitmq:
    host: 192.168.203.203
    port: 5672
    username: admin
    password: admin
    virtualHost: /
    publisher-returns: true
    #发送端确认；
    publisher-confirm-type: correlated
    #手动ack机制
    listener:
      type: simple
      simple:
        acknowledge-mode: manual  #手动确认模式。

app:
  props:
    ware-url: http://localhost:14000

