server:
  port: 7000

#数据源
spring:
  datasource:
    url: jdbc:mysql://192.168.203.203:3306/gmall_product?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.203.203
    password: Hj123!@!
    lettuce:
      pool:
        max-active: 16
        min-idle: 0

#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*.xml

app:
  minio:
    endpoint: http://192.168.203.203:9000
    accessKey: admin
    secretKey: admin123456
    bucket: gmall